---
bibliography: references.bib
---

# The Problem


## What the problem is

There is currently no R package that provides ready-to-use pre-trained model for time series forecasting. 

## Who it affects

There is a rich tidyverse[@tidyverse] friendly time series analysis pipeline called tidyverts. This contains tsibble [@tsibble], fable [@fable], fabletools [@fabletools] R packages that helps for data structures for storing time series data, functions to do data wrangling, and functions for time series forecasting. Pre-trained models are widely used across many domains today. This is a very effective approach for time series forecasting particularly with limited data. Even though R has already established a rich ecosystem for time series forecasting, the unavailability of pre-trained models makes R users to shift to alternative programming languages or limit their ability to use this efficient method for time series forecasting. 


## Why is it a problem

It becomes a problem because the absence of pre-trained models changes forecasting from a quick, accessible task into a slow, expertise-heavy process. This also makes R users underutilization of advanced methods. This forces R users to stick to forecasts models such as ARIMA, ETS, Neural Networks, Prophet, etc. In otherowrds, this limits the accessibility of modern forecasting methods for R users.

## What will solving the problem enable (why should it be solved)

In this work we will develop a light weight pre-trained model for epidemiology time series forecasting. To train the pre-trained model I will use epidemiology counts data published by health ministries, institutions, etc. across multiple countries.  For example, Epidemiology Unit, Ministry of Health, Sri Lanka published weekly epidemilogy reports as of [here](https://www.epid.gov.lk/weekly-epidemiological-report/weekly-epidemiological-report) corresponds to the following diseases:

- Dengue fever

- Dysentery

- Encephalitis

- Encephalitis fever

- Food Poison

- Leptospirosis

- Typhus

- Viral Hepatitis

- H. Rabies

- Chickenpox

- Meningitis

- Leishman

- Tubeculosis

- Leprosy

I will be using all these weekly counts to my pre-trained model database. Inaddition to I will collect data from the following websites:

[Institute for Health Metrics and Evaluation](https://vizhub.healthdata.org/gbd-results/)

[WHO Tuberculosis  database](https://www.who.int/teams/global-tuberculosis-programme/data)
 
[https://opendengue.org/](https://opendengue.org/)

I will also explore freely available open-access databases for data collection. Crrently, there is no single global website that contains clean “ready-made counts” for all these diseases together.
 
## Brief summary of existing work and previous attempts (e.g., relevant R packages)

Previous packages:

`denguedatahub` R package: I compiled dengue data for 216 countries and compiled into a package called denguedatahub. The project website is at [https://denguedatahub.netlify.app/](https://denguedatahub.netlify.app/). This project is funded by RConortium ISC 2022 grant. Since 2022, I am maintaining this project. This dataset will also be used train the odel.

`DISC`: The R package I developed [https://github.com/SMART-Research/DISC](https://github.com/SMART-Research/DISC) contains disese counts for Dysentery, Encephalitis, Encephalitis fever, Food Poison, Leptospirosis, Typhus, Viral Hepatitis, H. Rabies, Chickenpox, Meningitis, Leishman, Tubeculosis and Leprosy. This will also be used in pre-trained model development.

`seer` package: The seer package provides implementations of a novel framework for forecast model selection using time series features. We call this framework FFORMS (Feature-based FORecast Model Selection). For more details see our [paper](https://onlinelibrary.wiley.com/doi/abs/10.1002/for.2963). The R package repository is: [https://github.com/thiyangt/seer](https://github.com/thiyangt/seer). This is a joint work with Prof Rob Hyndman and Prof George Athanasopoulos

`vegcast`: Feature engineering to train a pre-trained model for vegetable price forecasting. This work is part of the project funded by [https://forecasters.org/programs/research-awards/forecasting-for-social-good-research-grant/](https://forecasters.org/programs/research-awards/forecasting-for-social-good-research-grant/). I am the 2025 F4SG grant receipient as listed on the website. The github repositoy of the project [https://github.com/thiyangt/vegcast](https://github.com/thiyangt/vegcast).  The project repository is [https://thiyangt.github.io/pricecast.vegetables/](https://thiyangt.github.io/pricecast.vegetables/).

`tsdataleaks`: R package to identify data leaks in time series data available at: [https://github.com/thiyangt/tsdataleaks](https://github.com/thiyangt/tsdataleaks)

`vegetablesSriLanka`: R package for vegetable prices in Sri Lanka. Link [https://github.com/thiyangt/vegetablesSriLanka](https://github.com/thiyangt/vegetablesSriLanka)

In addition to there are many other packages I developed and published on CRAN.

## If proposing changes to R itself: letter of support from R Core member

No changes to R


